tap "adoptopenjdk/openjdk"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
cask "adoptopenjdk"
brew "ack"
brew "carthage"
brew "genact"
brew "git"
brew "hub"
brew "imagemagick"
brew "ios-deploy"
brew "jq"
brew "librsvg"
brew "mas"
brew "pre-commit"
brew "pyenv-virtualenv"
brew "rbenv"
brew "sonar-scanner"
brew "swiftlint"
brew "tailor"
cask "bluestacks"
cask "caprine"
cask "charles"
cask "dash"
cask "dropbox"
cask "firefox"
cask "google-backup-and-sync"
cask "google-chrome"
cask "intel-power-gadget"
cask "iterm2"
cask "keycastr"
cask "obs"
cask "sketch"
cask "slack"
cask "sourcetree"
cask "adoptopenjdk/openjdk/adoptopenjdk8"
mas "1Password 7", id: 1333542190
mas "AdBlock", id: 1402042596
mas "Dynamo", id: 1445910651
mas "Fantastical", id: 975937182
mas "LINE", id: 539883307
mas "Magnet", id: 441258766
mas "Xcode", id: 497799835
